//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mop.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int ID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string AtributeName { get; set; }
        public string ItemEditted { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Checking { get; set; }
        public Nullable<bool> Done { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
